apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string

  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      runAfter:
        - init
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: npminstall
      runAfter:
        - clone
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      runAfter:
        - tests
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)
      workspaces:
        - name: source
          workspace: pipeline-workspace
